config/routes.rb
MishDinners::Application.routes.draw do
  root 'pages#home'

  resources :calendars, :only => [:show, :edit, :update] do
    get 'print', on: :member

    resources :volunteers,         :only => [:index]
    resources :reminder_emailings, :only => [:create]
  end

  resources :settings,  :only => [:edit, :update]

  if Rails.env.development?
    get '/rails/info/properties' => "rails/info#properties"
    get '/rails/info/routes'     => "rails/info#routes"
    get '/rails/info'            => "rails/info#index"
  end

  get "/secret/exception/raiser/:secret" => 'test_exceptions#show', contraints: {secret: ENV['EXCEPTION_TEST_SECRET']}

  get ':division_abbr/:unit_abbr/print' => 'calendars#print'
  get ':division_abbr/:unit_abbr/edit'  => 'calendars#edit'
  get ':division_abbr/:unit_abbr'       => 'calendars#show'
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_unit,  only: [:edit, :update]
  before_action :authorize, only: [:edit, :update]

  def edit
    @calendar = Calendar.new(@unit)
  end

  def update
    @calendar = Calendar.new(@unit)
    if @settings.update(settings_params)
      redirect_to edit_calendar_url(@calendar, uuid: @calendar.unit_uuid),
                  notice: 'Settings were successfully updated.'
    else
      render action: 'edit'
    end
  end

  private

  def authorize
    raise ActiveRecord::RecordNotFound unless params[:uuid].present?
    raise ActiveRecord::RecordNotFound unless params[:uuid] == @unit.uuid
  end

  def set_unit
    @unit = Unit.find(params[:id])
    @settings = Settings.new(@unit)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def settings_params
    params.
      require(:settings).
      permit(:coordinator_name,
             :coordinator_email,
             :meal_time,
             :volunteer_pitch,
             :reminder_subject,
             :number_of_recipients,
             *((1..Rails.configuration.max_recipients).map {|i| "recipient#{i}_name"}),
             *((1..Rails.configuration.max_recipients).map {|i| "recipient#{i}_initials"}),
             *((1..Rails.configuration.max_recipients).map {|i| "recipient#{i}_phone"}))
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= simple_form_for @settings,
                    html: {:class => 'settings'},
                    url: setting_path(@settings, uuid: @settings.unit_uuid) do |f| %>
  <%= f.error_notification %>

  <%= f.input :volunteer_pitch, as: :text, hint: 'HTML tags allowed' %>
  <%= f.input :meal_time, hint: 'HTML tags allowed', input_html: {size: 95} %>
  <%= f.input :reminder_subject, label: 'Reminder email subject', input_html: {size: 50} %>
  <%= f.input :coordinator_name, input_html: {size: 50} %>
  <%= f.input :coordinator_email, input_html: {size: 50} %>

  <% recipients_title = Figaro.env.recipient_title.to_s.pluralize %>
  <fieldset>
    <legend><%= recipients_title %></legend>
    <%= f.input :number_of_recipients,
                label: "Number of #{recipients_title.downcase}",
                collection: 1..Rails.configuration.max_recipients,
                as: :radio_buttons,
                input_html: {:class                 => 'recipient_count_radio_btn',
                             'data-orig-count'      => f.object.number_of_recipients,
                             'data-recipient-title' => Figaro.env.recipient_title.to_s.downcase} %>

    <% (1..Rails.configuration.max_recipients).each do |recipient_number| %>
      <%= render :partial => 'recipient', locals: {f: f, recipient_number: recipient_number, settings: @settings} %>
    <% end %>
  </fieldset>

  <div class="actions">
    <%= f.button :submit, "Save" %>
    <%= link_to 'Cancel', edit_calendar_path(@calendar, uuid: @calendar.unit_uuid) %>
  </div>
<% end %>

app/views/settings/_recipient.html.erb
<% appropriate_style = recipient_number > settings.number_of_recipients ? 'display: none;' : '' %>

<div data-recipient-number="<%= recipient_number %>" style="<%= appropriate_style %>">
  <hr/>
  <%= f.input "recipient#{recipient_number}_name",
              label: "#{recipient_label(recipient_number)} label",
              hint: "defaults to '#{recipient_title(recipient_number)}'",
              input_html: {size: 12} %>

  <%= f.input "recipient#{recipient_number}_initials",
              label: "#{recipient_label(recipient_number)} initials",
              hint: "defaults to '#{recipient_abbreviation(recipient_number)}'",
              input_html: {size: 2} %>

  <%= f.input "recipient#{recipient_number}_phone",
              label: "#{recipient_label(recipient_number)} phone",
              input_html: {size: 12} %>

</div>

app/views/settings/edit.html.erb
<h1>Settings</h1>

<%= render 'form' %>